package:
    name: cbc
    version: 2.8.8

source:
    fn: Cbc-2.8.8.tgz
    url: http://www.coin-or.org/download/source/Cbc/Cbc-2.8.8.tgz

build:
    number: 1

about:
    home: http://www.coin-or.org/Cbc
    license: Eclipse Public License 
